### ISSUE TITLE
Words displayed in fullscreen are not centered

### ISSUE THREAD

**Issue by MKolman** [MKolman/mkolman.github.io#12]
Fix `showFullscreenText` function to display all the words centered on the screen.

Also `type` function on mobile only displays the correct size of words on second try.

**Comment by MKolman** [comment]
Use 
```CSS
.fullscreenify.vertical {
  writing-mode: vertical-rl;
  text-orientation: sideways;
}
```
to rotate text with CSS.
